### PR TITLE
issue#72 fix breadcrumb, remove hyphens and Capitalise first letter o…

### LINKED ISSUE #72: frontend: fix breadcrumb, remove hyphens and Capitalise first letter of first word

### PR DESCRIPTION
**Pull request by Jerry-1947**
Resolves #72

### CODE REVIEW

File: frontend/src/components/DynamicBreadcrumbs.js [hunk 1]
```diff
@@ -3,6 +3,10 @@ import Breadcrumbs from "react-router-dynamic-breadcrumbs";
 
 const routes = {
   "/": "Home",
+  "/:grandParentCategory": (url, match) => `${match[':grandParentCategory'].replace('-', ' ')[0].toUpperCase()}${match[':grandParentCategory'].replace('-', ' ').slice(1)}`,
+  "/:grandParentCategory/:parentCategory": (url, match) => `${match[':parentCategory'].replace('-', ' ')[0].toUpperCase()}${match[':parentCategory'].replace('-', ' ').slice(1)}`,
+  "/:grandParentCategory/:parentCategory/:childCategory": (url, match) => `${match[':childCategory'].replace('-', ' ')[0].toUpperCase()}${match[':childCategory'].replace('-', ' ').slice(1)}`,
+  "/:grandParentCategory/:parentCategory/:childCategory/:slug": (url, match) => `${match[':slug'].replace('-', ' ')[0].toUpperCase()}${match[':slug'].replace('-', ' ').slice(1)}`,
   "/:id": ":id",
```
Comment (ashdaily) [inline frontend/src/components/DynamicBreadcrumbs.js:10]: create a utility function you can reuse again and again inside `util/Helper.js` , it will be much cleaner to reuse:

```
const removeHyphenAndCapitalize = (url) => url.replace('-', ' ')[0].toUpperCase()
```

**Review by ashdaily — CHANGES_REQUESTED** [review]
